package com.pzc.navigationweb.dao;

import com.pzc.navigationweb.domain.dbdo.FavoritesDO;
import org.apache.ibatis.annotations.Param;

public interface FavoritesDOMapper {

    FavoritesDO selectByUserNavId(@Param("userId") String userId, @Param("navId") String navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    int insert(FavoritesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    int insertSelective(FavoritesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    FavoritesDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    int updateByPrimaryKeySelective(FavoritesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated Tue May 18 00:50:58 CST 2021
     */
    int updateByPrimaryKey(FavoritesDO record);
}