package com.pzc.navigationweb.dao;

import com.pzc.navigationweb.domain.dbdo.LotteryDO;

public interface LotteryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    int insert(LotteryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    int insertSelective(LotteryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    LotteryDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    int updateByPrimaryKeySelective(LotteryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    int updateByPrimaryKey(LotteryDO record);
}