server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/navigation_resources?characterEncoding=utf-8
    username: root
    password: ryfla123mysql
    driverClassName: com.mysql.jdbc.Driver
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池名称，默认HikariPool-1
    pool-name: CoreHikariPool
    #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
    #hikari:
    maximum-pool-size: 100
    #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
    connection-timeout: 60000
    #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
    minimum-idle: 20
    #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
    # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
    idle-timeout: 300000
    #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
    max-lifetime: 340000
    #连接测试查询
    connection-test-query:  SELECT 1
  application:
    name: navigation-center-service
