package com.pzc.navigationweb.domain.dbdo;

import java.util.Date;

public class LotteryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.create_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.create_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.create_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String createAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.create_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.modify_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.modify_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String modifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.modify_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String modifyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.modify_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String modifyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.is_del
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private Byte isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.version
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.event_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String eventDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.normal_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String normalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.special_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private String specialNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.type
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.id
     *
     * @return the value of lottery.id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.id
     *
     * @param id the value for lottery.id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.create_date
     *
     * @return the value of lottery.create_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.create_date
     *
     * @param createDate the value for lottery.create_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.create_id
     *
     * @return the value of lottery.create_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.create_id
     *
     * @param createId the value for lottery.create_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.create_account
     *
     * @return the value of lottery.create_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getCreateAccount() {
        return createAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.create_account
     *
     * @param createAccount the value for lottery.create_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setCreateAccount(String createAccount) {
        this.createAccount = createAccount == null ? null : createAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.create_name
     *
     * @return the value of lottery.create_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.create_name
     *
     * @param createName the value for lottery.create_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.modify_date
     *
     * @return the value of lottery.modify_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.modify_date
     *
     * @param modifyDate the value for lottery.modify_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.modify_id
     *
     * @return the value of lottery.modify_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.modify_id
     *
     * @param modifyId the value for lottery.modify_id
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.modify_account
     *
     * @return the value of lottery.modify_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.modify_account
     *
     * @param modifyAccount the value for lottery.modify_account
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount == null ? null : modifyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.modify_name
     *
     * @return the value of lottery.modify_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.modify_name
     *
     * @param modifyName the value for lottery.modify_name
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.is_del
     *
     * @return the value of lottery.is_del
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.is_del
     *
     * @param isDel the value for lottery.is_del
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.version
     *
     * @return the value of lottery.version
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.version
     *
     * @param version the value for lottery.version
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.event_date
     *
     * @return the value of lottery.event_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.event_date
     *
     * @param eventDate the value for lottery.event_date
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setEventDate(String eventDate) {
        this.eventDate = eventDate == null ? null : eventDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.normal_num
     *
     * @return the value of lottery.normal_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getNormalNum() {
        return normalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.normal_num
     *
     * @param normalNum the value for lottery.normal_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setNormalNum(String normalNum) {
        this.normalNum = normalNum == null ? null : normalNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.special_num
     *
     * @return the value of lottery.special_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public String getSpecialNum() {
        return specialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.special_num
     *
     * @param specialNum the value for lottery.special_num
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setSpecialNum(String specialNum) {
        this.specialNum = specialNum == null ? null : specialNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.type
     *
     * @return the value of lottery.type
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.type
     *
     * @param type the value for lottery.type
     *
     * @mbg.generated Fri Aug 13 11:23:18 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }
}